version: 2
jobs:
  build:
    docker: #  tircleci/node:10.0.0 # the primary container, where your job's commands are run
        - image: circleci/node:10.0.0  # run in the background
    steps:
      - checkout # check out the code in the project directory
      - run: npm install 
      - run: npm start & 
      - run: npm test 
      - deploy:
          name: aws
          command: ssh -i "gap.pem" -o "StrictHostKeyChecking no" ubuntu@ec2-54-183-19-243.us-west-1.compute.amazonaws.com "cd ~/circleciexpress; git pull; npm install; npm start &"
