version: 2
jobs:
  build:
    docker: #  tircleci/node:10.0.0 # the primary container, where your job's commands are run
        - image: circleci/node:10.0.0  # run in the background
    steps:
      - checkout # check out the code in the project directory
      - run: npm install 
      - run: npm start & 
      - run: npm test 
      - deploy:
          name: aws
          command: ssh -o "StrictHostKeyChecking no" ubuntu@54.183.19.243"cd ~/circleciexpress; git pull; npm install; npm start &"
  
